Add files via upload
It won't let me push .
This is what it says:
To github.com:ece-231l-fall-2019/week-1-github-hquang1999.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:ece-231l-fall-2019/week-1-github-hquang1999.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.